image: python:3.8

stages:
  - test
  - deploy

test:
  stage: test
  script: 
    - pip install kedro==0.16.6
    - kedro install
    - kedro test

environnement-test:
  stage: deploy
  script: 
    - echo "$GITLAB_SERVICE_ACCOUNT_KEY"


  