apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-coco-bebe
spec:
  selector:
    matchLabels:
      app: colibrimmo-group-1
  template:
    metadata:
      labels:
        app: colibrimmo-group-1
    spec:
      containers:
      - name: colibrimmo-group-1
        image: eu.gcr.io/yotta-mlops/kubernetes-batman:ex4
        volumes:
        - name: secret-group-1
          secret:
            secretName: secret-group-1
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database

      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command: 
          - "/cloud_sql_proxy" 
          - "-instances=yotta-mlops:europe-west1:group-1=tcp:5432"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: secret-group-1
          mountPath: /conf/local/
          readOnly: true