apiVersion: v1
kind: Service
metadata:
  name: colibrimmo-group-1-svc
spec:
  type: LoadBalancer
  selector:
    name: colibrimmo-group-1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000