apiVersion: v1
kind: Service
metadata:
  name: colibrimmo-group-1-svc-__BRANCHNAME__
spec:
  type: LoadBalancer
  selector:
    name: colibrimmo-group-1
    version: __BRANCHNAME__
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000